CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Files" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "FullPath" text NOT NULL,
    "InternalName" text NOT NULL,
    "ContentType" text NOT NULL,
    "Size" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Files" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Files_FullPath" ON "Files" ("FullPath");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241129192526_Initial_Create', '9.0.0');

COMMIT;
